name : backend

on:
  push:
    branches:
     - main

defaults:
  run:
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Checkout the repository
      - uses: actions/setup-node@v3 # Setup Node.js
        with:
          node-version: 24.x # Specify the Node.js version

      - run: npm ci # Install dependencies
      - run: npm run test # Run tests
      - run: npm run build # Build the project