name : backend

on:
  push:
    branches:
     - main

defaults:
  run:
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout and Setup'
        uses: actions/checkout@v7 # Checkout the repository
        uses: actions/setup-node@v6 # Setup Node.js
        with:
          node-version: 24.x # Specify the Node.js version

      - name: 'Install Dependencies and Run Tests'
        run: |
          npm ci # Install dependencies
          npm run test # Run tests
          npm run build # Build the project

      - name: 'Upload Coverage Artifact'
        uses: actions/upload-artifact@v7
        with:
          name: coverage
          path: backend/coverage/**
          retention-days: 5

      - name: 'Upload dist Artifact'
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: backend/dist/index.js
          retention-days: 5
